
// def readYaml(String readYamlFilePath) {
//     """
//     Function to read key-value pairs from a YAML file and return them as a map.
//     """
//     if (fileExists(readYamlFilePath)) {
//         return readYaml(file: readYamlFilePath)
//     } else {
//         error "File $readYamlFilePath not found in the workspace!"
//     }
// }

def readVarsFromYaml(String readYamlFilePath){
    """
    Función para leer variables llave valor(String) desde un archivo yaml
    """
    if(fileExists(readYamlFilePath)){
        def yamlFile = readYaml file: "$readYamlFilePath"
        yamlFile.each { key, value ->
            env."$key" = value
            echo "Se crea variable $key = $value"
        }
    } else {
        error "No se encontró archivo $readYamlFilePath en el workspace!"
    }
}

pipeline {

    agent any

    environment {
        // BRANCHES = "^stage_(dev|qas|pro)_env_(dev|qas|pro)$"
        BRANCHES = "main"
    }
 
    stages {
        stage ("Initialize Pipeline") {
            when { branch pattern: BRANCHES, comparator: "REGEXP"; beforeAgent true }
            // agent { kubernetes { inheritFrom 'gcloud'; showRawYaml false } }
            

            steps {
               script { 
                    readVarsFromYaml("src/test/environments/variables.yaml") 
                    env.bucket = sh(script: "eval echo \$$BRANCH_NAME", returnStdout: true).trim()
                    echo "Se encuentra bucket: $bucket"
                }
                
            }
        }
    }
}  