// @Library([
//     'gcp-library@v1.0.0',
//     'common-library@v1.0.3'
// ]) _

def readVarsFromYaml(String readYamlFilePath){
    """
    Función para leer variables llave valor(String) desde un archivo yaml
    """
    if(fileExists(readYamlFilePath)){
        def yamlFile = readYaml file: "$readYamlFilePath"
        yamlFile.each { key, value ->
            env."$key" = value
            echo "Se crea variable $key = $value"
        }
    } else {
        error "No se encontró archivo $readYamlFilePath en el workspace!"
    }
}

pipeline {

    agent none

    environment {
        // BRANCHES = "^stage_(dev|qas|pro)_env_(dev|qas|pro)$"
        BRANCHES = "main"
    }
 
    stages {
        stage ("Initialize Pipeline") {
            when { branch pattern: BRANCHES, comparator: "REGEXP"; beforeAgent true }
            any { kubernetes { inheritFrom 'gcloud'; showRawYaml false } }
            

            steps {
               script { 
                    readVarsFromYaml("src/test/environments/variables.yaml") 
                    env.bucket = sh(script: "eval echo \$$BRANCH_NAME", returnStdout: true).trim()
                    echo "Se encuentra bucket: $bucket"
                }
                
            }
        }
        stage ("Update files") {
            when { branch pattern: BRANCHES, comparator: "REGEXP"; beforeAgent true }
            agent { kubernetes { inheritFrom 'gcloud'; showRawYaml false } }
            steps {
               container("gcloud") {
                    script {
                        readVarsFromYaml("jenkins/environments/variables.yaml") 
                        sh ("gcloud storage rsync . gs://$bucket --exclude='jenkins'")           
                    }
                }
            }
        }
    }
}  