apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: postfix-00031-7jh
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  containers:
  - name: server
    image: us-central1-docker.pkg.dev/labuniformes/test-cloud-run/smtp@sha256:d6955ce136fc1e7993d04dd383c1924527173e8b00a16393b16c18865a01e82f
    ports:
    - name: http1
      containerPort: 5000
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
    startupProbe:
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3
      httpGet:
        path: /
        port: 5000

