// NodeJS plugin https://plugins.jenkins.io/nodejs/   configurar en tools

// pipeline {
//     agent {
//         docker {
//             image 'node:lts-buster-slim'
//             args '-p 3000:3000'
//         }
//     }
    // environment {
    //     CI = 'true'
    // }
    // stages {
    //     stage('Build') {
    //         steps {
    //             dir('src/react') {
    //                 sh 'npm install'
    //             }
    //         }
    //     }
        // stage('Test') {
        //     steps {
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //         input message: 'Finished using the web site? (Click "Proceed" to continue)'
        //         sh './jenkins/scripts/kill.sh'
        //     }
        // }
//     }
// }

pipeline {
    agent { 
        dockerfile {
            filename 'Dockerfile'
            dir "src/react"
        }
    }
    stages {
        stage ('Uno') {
            steps {
                echo 'hola mundo'
            }
        }
    }
}