

// pipeline {
//     agent { 
//         dockerfile {
//             filename 'Dockerfile'
//             dir "src/react"
//         }
//     }
//     stages {
//         stage ('Test') {
//             steps {
//                 echo 'hola mundo'
//             }
//         }
//     }
// }

pipeline {
    agent any
    environment {
        _REPOSITORY = "liverpool-portal-uniformes-dev-images-apps"
        _IMAGE = "frontend-uniformes-service"
        _LOCATION = "us-east4"
        _DESTINATION_PROJECT_ID = "sit-cicd-images-apps"
        _IMAGE_PATH = "us-east4-docker.pkg.dev/${_DESTINATION_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}"
        _PIPELINE_NAME = "frontend-uniformes-service-pipeline"
    }
    stages {
        stage ('Test') {
            steps {
                dir('src/react') {
                    withCredentials([file(credentialsId: 'key-sa', variable: 'GC_KEY')]) {
                        sh("gcloud auth activate-service-account --key-file=${GC_KEY}")
                        sh("docker build -t ${_IMAGE_PATH} .")
                    }
                }
            }
        }
    }
}
